module HighLevel(
	O_en);

	//---Ports declearation: generated by Robei---
	output O_en;

	wire O_en;

	//----Code starts here: integrated by Robei-----
	assign O_en=1;
	
	
	
endmodule    //HighLevel

