module Move_CTR(
	CLK,
	state,
	key,
	PWM1A,
	PWM1H,
	PWM1L,
	PWM2A,
	PWM2H,
	PWM2L,
	PWM3A,
	PWM3H,
	PWM3L,
	PWM4A,
	PWM4H,
	PWM4L,
	PWM5A,
	PWM5H,
	PWM5L,
	en,
	led);

	//---Ports declearation: generated by Robei---
	input CLK;
	input [3:0] key;
	input [1:0] state;
	output PWM1A;
	output PWM1H;
	output PWM1L;
	output PWM2A;
	output PWM2H;
	output PWM2L;
	output PWM3A;
	output PWM3H;
	output PWM3L;
	output PWM4A;
	output PWM4H;
	output PWM4L;
	output PWM5A;
	output PWM5H;
	output PWM5L;
	input en;

	
	
	output [3:0] led;
	
	
	
	wire CLK;
	wire [1:0] state;
	wire [3:0] key;
	wire PWM1A;
	wire PWM1H;
	wire PWM1L;
	wire PWM2A;
	wire PWM2H;
	wire PWM2L;
	wire PWM3A;
	wire PWM3H;
	wire PWM3L;
	wire PWM4A;
	wire PWM4H;
	wire PWM4L;
	wire PWM5A;
	wire PWM5H;
	wire PWM5L;
	
	wire en;
	wire [7:0] duty_decoder9_A1duty;
	
	wire [7:0] duty_decoder9_A2duty;
	
	wire [7:0] duty_decoder9_A3duty;

	wire [7:0] duty_decoder9_A4duty;
	
	wire [7:0] duty_decoder9_A5duty;
	
	/*
	wire [7:0] duty_decoder9_A2duty;
	wire [7:0] duty_decoder9_B2duty;
	wire [7:0] duty_decoder9_A3duty;
	wire [7:0] duty_decoder9_B3duty;
	wire [7:0] duty_decoder9_A4duty;
	wire [7:0] duty_decoder9_B4duty;
	*/

	//----Code starts here: integrated by Robei-----
	
	
	
	//---Module instantiation---
	PWM PWM1(
		.CLK(CLK),
		.duty (duty_decoder9_A1duty),
		.PWMOUT(PWM1A));

	PWM PWM2(
		.CLK(CLK),
		.duty (duty_decoder9_A2duty),
		.PWMOUT(PWM2A));
	PWM PWM3(
		.CLK(CLK),
		.duty (duty_decoder9_A3duty),
		.PWMOUT(PWM3A));

	PWM PWM4(
		.CLK(CLK),
		.duty (duty_decoder9_A4duty),
		.PWMOUT(PWM4A));
		
		PWM PWM5(
		.CLK(CLK),
		.duty (duty_decoder9_A5duty),
		.PWMOUT(PWM5A));
/*
	PWM PWM5(
		.CLK(CLK),
		.duty (duty_decoder9_A3duty),
		.PWMOUT(PWM3A));

	PWM PWM6(
		.CLK(CLK),
		.duty (duty_decoder9_B3duty),
		.PWMOUT(PWM3B));

	PWM PWM7(
		.CLK(CLK),
		.duty (duty_decoder9_A4duty),
		.PWMOUT(PWM4A));

	PWM PWM8(
		.CLK(CLK),
		.duty (duty_decoder9_B4duty),
		.PWMOUT(PWM4B));
*/
	duty_decoder duty_decoder9(
		.state(state),
		.key(key),
		.A1duty(duty_decoder9_A1duty),
		.A2duty(duty_decoder9_A2duty),
		.A3duty(duty_decoder9_A3duty),
		.A4duty(duty_decoder9_A4duty),
		
		.A5duty(duty_decoder9_A5duty),
		.PWM1H(PWM1H),
		.PWM1L(PWM1L),
		.PWM2H(PWM2H),
		.PWM2L(PWM2L),
		.PWM3H(PWM3H),
		.PWM3L(PWM3L),
		.PWM4H(PWM4H),
		.PWM4L(PWM4L),
		.PWM5H(PWM5H),
		.PWM5L(PWM5L),

		.en(en),
		.led(led));

endmodule    //Move_CTR

