module MUX(
	select2,
	init_data,
	init_en,
	run_data,
	run_en,
	stop_data,
	stop_en,
	left_data,
	left_en,
	right_data,
	right_en,
	O_data,
	O_en,
	select3,
	select4,
	select1,
	select5);

	//---Ports declearation: generated by Robei---
	input select2;
	input [7:0] init_data;
	input init_en;
	input [7:0] run_data;
	input run_en;
	input [7:0] stop_data;
	input stop_en;
	input [7:0] left_data;
	input left_en;
	input [7:0] right_data;
	input right_en;
	output [7:0] O_data;
	output O_en;
	input select3;
	input select4;
	input select1;
	input select5;

	wire select2;
	wire [7:0] init_data;
	wire init_en;
	wire [7:0] run_data;
	wire run_en;
	wire [7:0] stop_data;
	wire stop_en;
	wire [7:0] left_data;
	wire left_en;
	wire [7:0] right_data;
	wire right_en;
	reg [7:0] O_data;
	reg O_en;
	wire select3;
	wire select4;
	wire select1;
	wire select5;

	//----Code starts here: integrated by Robei-----
	always@(*)
	begin
		case({select1,select2,select3,select4,select5})
		5'b10000:begin	O_data=init_data;O_en=init_en;end
		5'b01000:begin	O_data=run_data;O_en=run_en;end
		5'b00100:begin	O_data=stop_data;O_en=stop_en;end
		5'b00010:begin	O_data=left_data;O_en=left_en;end
		5'b00001:begin	O_data=right_data;O_en=right_en;end
		default:;
		endcase
	end
	
	
	
endmodule    //MUX

