module RB_Final(
	I_clk,
	I_rst_n,
	I_barrier,
	PWM1A,
	PWM1H,
	PWM1L,
	PWM2A,
	PWM2H,
	PWM2L,
	PWM3A,
	PWM3H,
	PWM3L,
	PWM4A,
	PWM4H,
	PWM4L,
	PWM5A,
	PWM5H,
	PWM5L,
	O_scl,
	IO_sda,
	key,
	I_turn_left,
	I_turn_right,
	led);

	//---Ports declearation: generated by Robei---
	input I_clk;
	input I_rst_n;
	input I_barrier;
	input key;
	input I_turn_left;
	input I_turn_right;
	output PWM1A;
	output PWM1H;
	output PWM1L;
	output PWM2A;
	output PWM2H;
	output PWM2L;
	output PWM3A;
	output PWM3H;
	output PWM3L;
	output PWM4A;
	output PWM4H;
	output PWM4L;
		output PWM5A;
	output PWM5H;
	output PWM5L;
	output O_scl;
	inout IO_sda;

	
	
	
	output led;
	
	
	
	
	
	wire I_clk;
	wire I_rst_n;
	wire I_turn_left;
	wire I_turn_right;
	wire I_barrier;
	wire [3:0] key;
	wire [3:0] led;
	
	
	wire PWM1H;
	wire PWM1L;
	
	
	wire PWM1A;
	//wire PWM1H;
	//wire PWM1L;
	wire PWM2A;
	//wire PWM2H;
	//wire PWM2L;
	wire PWM3A;
	//wire PWM3H;
	//wire PWM3L;
	wire PWM4A;
	//wire PWM4H;
	//wire PWM4L;
	wire PWM5A;
	wire O_scl;
	wire IO_sda;
	wire [1:0] aviodLogic1_state;
	wire HighLevel4_O_en;

	
	
	//reg [3:0] led;
	
	
	
	//----Code starts here: integrated by Robei-----
	
	
	
	
	//---Module instantiation---
	aviodLogic aviodLogic1(
		.I_clk(I_clk),
		.I_rst_n(I_rst_n),
		.I_barrier(I_barrier),
		.state(aviodLogic1_state),
		.I_turn_left(I_turn_left),
		.I_turn_right(I_turn_right),);

	Move_CTR Move_CTR2(
		.CLK(I_clk),
		.state(aviodLogic1_state),
		.PWM1A(PWM1A),
		.PWM1H(PWM1H),
		.PWM1L(PWM1L),
		.PWM2A(PWM2A),
		.PWM2H(PWM2H),
		.PWM2L(PWM2L),
		.PWM3A(PWM3A),
		.PWM3H(PWM3H),
		.PWM3L(PWM3L),
		.PWM4A(PWM4A),
		.PWM4H(PWM4H),
		.PWM4L(PWM4L),
		.PWM5A(PWM5A),
		.PWM5H(PWM5H),
		.PWM5L(PWM5L),
		.en(HighLevel4_O_en),
		.key(key),
		.led(led));

	voice_play_cptBlock voice_play_cptBlock3(
		.I_clk(I_clk),
		.I_rst_n(I_rst_n),
		.I_en(HighLevel4_O_en),
		.select(aviodLogic1_state),
		.O_scl(O_scl),
		.IO_sda(IO_sda));

	HighLevel HighLevel4(
		.O_en(HighLevel4_O_en));

endmodule    //RB_Final

