module voice_play_cptBlock(
	I_clk,
	I_rst_n,
	I_en,
	select,
	O_scl,
	O_sda_mode,
	IO_sda);

	//---Ports declearation: generated by Robei---
	input I_clk;
	input I_rst_n;
	input I_en;
	input [1:0] select;
	output O_scl;
	output O_sda_mode;
	inout IO_sda;

	wire I_clk;
	wire I_rst_n;
	wire I_en;
	wire [1:0] select;
	wire O_scl;
	wire O_sda_mode;
	wire IO_sda;
	wire play_init2_O_Byte_done;
	wire play_qianjin3_O_Byte_done;
	wire play_tingzhi4_O_Byte_done;
	wire play_zuozhuan6_O_Byte_done;
	wire play_youzhuan5_O_Byte_done;
	wire iic_send1_O_done_flag;
	wire voice_play_control7_init_en;
	wire voice_play_control7_init_rst_n;
	wire voice_play_control7_run_en;
	wire voice_play_control7_run_rst_n;
	wire voice_play_control7_stop_en;
	wire voice_play_control7_stop_rst_n;
	wire voice_play_control7_left_en;
	wire voice_play_control7_left_rst_n;
	wire voice_play_control7_right_en;
	wire voice_play_control7_right_rst_n;
	wire [7:0] MUX8_O_data;
	wire MUX8_O_en;
	wire [7:0] play_init2_O_data;
	wire play_init2_O_iic_send_en;
	wire [7:0] play_qianjin3_O_data;
	wire play_qianjin3_O_iic_send_en;
	wire [7:0] play_tingzhi4_O_data;
	wire play_tingzhi4_O_iic_send_en;
	wire [7:0] play_zuozhuan6_O_data;
	wire play_zuozhuan6_O_iic_send_en;
	wire [7:0] play_youzhuan5_O_data;
	wire play_youzhuan5_O_iic_send_en;

	//----Code starts here: integrated by Robei-----
	
	
	
	
	//---Module instantiation---
	iic_send iic_send1(
		.I_clk(I_clk),
		.I_rst_n(I_rst_n),
		.I_write_data(MUX8_O_data),
		.I_iic_send_en(MUX8_O_en),
		.O_scl(O_scl),
		.O_done_flag(iic_send1_O_done_flag),
		.O_sda_mode(O_sda_mode),
		.IO_sda(IO_sda));

	play_qianjin play_qianjin3(
		.I_clk(I_clk),
		.I_en(voice_play_control7_run_en),
		.I_rst_n(voice_play_control7_run_rst_n),
		.I_done_flag(iic_send1_O_done_flag),
		.O_data(play_qianjin3_O_data),
		.O_iic_send_en(play_qianjin3_O_iic_send_en),
		.O_Byte_done(play_qianjin3_O_Byte_done));

	play_tingzhi play_tingzhi4(
		.I_clk(I_clk),
		.I_en(voice_play_control7_stop_en),
		.I_rst_n(voice_play_control7_stop_rst_n),
		.I_done_flag(iic_send1_O_done_flag),
		.O_data(play_tingzhi4_O_data),
		.O_iic_send_en(play_tingzhi4_O_iic_send_en),
		.O_Byte_done(play_tingzhi4_O_Byte_done));

	play_youzhuan play_youzhuan5(
		.I_clk(I_clk),
		.I_en(voice_play_control7_right_en),
		.I_rst_n(voice_play_control7_right_rst_n),
		.I_done_flag(iic_send1_O_done_flag),
		.O_data(play_youzhuan5_O_data),
		.O_iic_send_en(play_youzhuan5_O_iic_send_en),
		.O_Byte_done(play_youzhuan5_O_Byte_done));

	play_zuozhuan play_zuozhuan6(
		.I_clk(I_clk),
		.I_en(voice_play_control7_left_en),
		.I_rst_n(voice_play_control7_left_rst_n),
		.I_done_flag(iic_send1_O_done_flag),
		.O_data(play_zuozhuan6_O_data),
		.O_iic_send_en(play_zuozhuan6_O_iic_send_en),
		.O_Byte_done(play_zuozhuan6_O_Byte_done));

	play_init play_init2(
		.I_clk(I_clk),
		.I_en(voice_play_control7_init_en),
		.I_rst_n(voice_play_control7_init_rst_n),
		.I_done_flag(iic_send1_O_done_flag),
		.O_data(play_init2_O_data),
		.O_iic_send_en(play_init2_O_iic_send_en),
		.O_Byte_done(play_init2_O_Byte_done));

	voice_play_control voice_play_control7(
		.I_clk(I_clk),
		.I_rst_n(I_rst_n),
		.I_en(I_en),
		.select(select),
		.init_en(voice_play_control7_init_en),
		.init_rst_n(voice_play_control7_init_rst_n),
		.run_en(voice_play_control7_run_en),
		.run_rst_n(voice_play_control7_run_rst_n),
		.stop_en(voice_play_control7_stop_en),
		.stop_rst_n(voice_play_control7_stop_rst_n),
		.left_en(voice_play_control7_left_en),
		.left_rst_n(voice_play_control7_left_rst_n),
		.right_en(voice_play_control7_right_en),
		.right_rst_n(voice_play_control7_right_rst_n),
		.init_done(play_init2_O_Byte_done),
		.run_done(play_qianjin3_O_Byte_done),
		.stop_done(play_tingzhi4_O_Byte_done),
		.left_done(play_zuozhuan6_O_Byte_done),
		.right_done(play_youzhuan5_O_Byte_done));

	MUX MUX8(
		.select2(voice_play_control7_run_en),
		.init_data(play_init2_O_data),
		.init_en(play_init2_O_iic_send_en),
		.run_data(play_qianjin3_O_data),
		.run_en(play_qianjin3_O_iic_send_en),
		.stop_data(play_tingzhi4_O_data),
		.stop_en(play_tingzhi4_O_iic_send_en),
		.left_data(play_zuozhuan6_O_data),
		.left_en(play_zuozhuan6_O_iic_send_en),
		.right_data(play_youzhuan5_O_data),
		.right_en(play_youzhuan5_O_iic_send_en),
		.O_data(MUX8_O_data),
		.O_en(MUX8_O_en),
		.select3(voice_play_control7_stop_en),
		.select4(voice_play_control7_left_en),
		.select1(voice_play_control7_init_en),
		.select5(voice_play_control7_right_en));

endmodule    //voice_play_cptBlock

